### ISSUE TITLE
Compatibility with higher java versions

### ISSUE THREAD

**Issue by NiklasEi** [aikar/commands#129]
An error was reported to me by @andris155, running one of my plugins in a Java 10 environment. From what I could find googling this, it should already be a problem in Java 9.

```[16:56:28] [Server thread/INFO]: [GameBox] Enabling GameBox v2.1.1
[16:56:28] [Server thread/INFO]: [GameBox] [ACF] Minecraft Version: 1.12
[16:56:28] [Server thread/ERROR]: Error occurred while enabling GameBox v2.1.1 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class me/nikl/gamebox/common/acf/RootCommand. Method lambda$addChildShared$0(Lcom/google/common/collect/SetMultimap;Lme/nikl/gamebox/common/acf/BaseCommand;Ljava/util/Map$Entry;)V at index 55 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at me.nikl.gamebox.common.acf.RootCommand.addChildShared(RootCommand.java:45) ~[?:?]
	at me.nikl.gamebox.common.acf.BukkitRootCommand.addChild(BukkitRootCommand.java:74) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.register(BaseCommand.java:285) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.registerSubcommand(BaseCommand.java:317) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.registerSubcommands(BaseCommand.java:254) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.onRegister(BaseCommand.java:145) ~[?:?]
	at me.nikl.gamebox.common.acf.BaseCommand.onRegister(BaseCommand.java:124) ~[?:?]
	at me.nikl.gamebox.common.acf.BukkitCommandManager.registerCommand(BukkitCommandManager.java:184) ~[?:?]
	at me.nikl.gamebox.commands.GameBoxCommands.registerCommand(GameBoxCommands.java:64) ~[?:?]
	at me.nikl.gamebox.commands.GameBoxCommands.registerCommands(GameBoxCommands.java:44) ~[?:?]
	at me.nikl.gamebox.commands.GameBoxCommands.<init>(GameBoxCommands.java:40) ~[?:?]
	at me.nikl.gamebox.GameBox.reload(GameBox.java:215) ~[?:?]
	at me.nikl.gamebox.GameBox.onEnable(GameBox.java:80) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1414]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [patched_1.12.2.jar:git-Paper-1414]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1414]
	at java.lang.Thread.run(Unknown Source) [?:?]
[16:56:28] [Server thread/INFO]: [GameBox] Disabling GameBox v2.1.1```

**Comment by aikar** [comment]
Yeah I've seen reports of this. This is honestly a JDK bug... Java is suppose to be backwards compat :/

I don't know what to do to fix it.

**Comment by aikar** [comment]
https://github.com/playframework/play-ws/pull/174

Looks like it may be relating to shading. I'll try updating shade plugin

**Comment by aikar** [comment]
I've pushed up updated plugins all around. This is all I really know I can do to fix this. The Shade plugin was a major version bump, so highly likely can fix it.

**Comment by aikar** [comment]
@NiklasEi please let me know if the issue is properly resolved now.

**Comment by NiklasEi** [comment]
@aikar 
I rebuilt GameBox with the newest 0.5.0-Snapshot yesterday, passed it on to @andris155 and he reported the same error as before.

Sorry, but it looks like the version bumps did not fix the problem.

**Comment by aikar** [comment]
@NiklasEi I've reopened but I think this has to do something with your own build - what is your own shade plugin versions?

One of my developers has ran our server under Java 10 successfully now....

**Comment by electronicboy** [comment]
https://github.com/NiklasEi/gamebox/blob/master/pom.xml#L53  If that's your project's pom, your version of shade is 3 years old now, I'd suggest upgrading to 3.1.1

**Comment by aikar** [comment]
Reclosing as it does appear to be your own build
See ACF versions of Shade/compiler: https://github.com/aikar/commands/blob/master/pom.xml

You are using the 2.x version of shade: https://github.com/NiklasEi/gamebox/blob/master/pom.xml#L50

**Comment by NiklasEi** [comment]
Sorry about that.
