### ISSUE TITLE
ACF breaking mcMMO

### ISSUE THREAD

**Issue by andrewkm** [aikar/commands#402]
Was told to report this here.
https://github.com/mcMMO-Dev/mcMMO/issues/4941
```
    @EventHandler
    public void onPlayerJoin(PlayerJoinEvent event) {
        Player player = event.getPlayer();
        if (this.manager.autoDetectFromClient) {
            this.manager.readPlayerLocale(player);
            this.manager.getScheduler().createDelayedTask(this.plugin, () -> manager.readPlayerLocale(player), 20);
        } else {
            this.manager.setIssuerLocale(player, this.manager.getLocales().getDefaultLocale());
            this.manager.notifyLocaleChange(this.manager.getCommandIssuer(player), null, this.manager.getLocales().getDefaultLocale());
        }
    }
```
is blowing up on this line:
`this.manager.readPlayerLocale(player);`

**Comment by chickeneer** [comment]
This should be fixed with a fresh compile. Let me know if it isn't.

**Comment by andrewkm** [comment]
> This should be fixed with a fresh compile. Let me know if it isn't.

Compiling mcMMO again didn't fix it for me, perhaps this requires @nossr50 to make some changes on the mcMMO side.

**Comment by chickeneer** [comment]
Well idk then. I was just working off of what someone else suggested as having changed. I don't have 1.20.2 up and going quite yet. So it'll be a few days before I can debug the issue.

**Comment by nakanotti** [comment]
I find it. "adventure$locale"

**Comment by chickeneer** [comment]
> I tried dump using `getDeclaredFields()` to find it. "adventure$locale"
> 
> ```
> --- a/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java
> +++ b/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java
> @@ -325,7 +325,7 @@ public class BukkitCommandManager extends CommandManager<
>                  try {
>                      localeField = nmsPlayer.getClass().getDeclaredField("locale");
>                  } catch (NoSuchFieldException ignored) {
> -                    localeField = nmsPlayer.getClass().getDeclaredField("language");
> +                    localeField = nmsPlayer.getClass().getDeclaredField("adventure$locale");
>                  }
>                  localeField.setAccessible(true);
>                  Object localeString = localeField.get(nmsPlayer);
> ```
> 
> After fixing acf-bukkit, I simply recompiled mcMMO and the exception no longer occurred.

No, that is wrong. You just found the `Locale` object field. Which conceivably we could migrate towards. Yours isn't throwing an exception because there is later an `instanceof String`. You just disabled the functionality altogether.
https://github.com/aikar/commands/blob/master/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java#L332

I don't know why reflection is being used here at all. Instead of just using the API. Well, obviously this was added before it was API, but still - that has probably not been the case for a while.

**Comment by nakanotti** [comment]
@chickeneer 
I see, thank you very much.
```
diff --git a/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java b/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java
index 3abe275e..4e0117ba 100755
--- a/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java
+++ b/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java
@@ -322,20 +322,29 @@ public class BukkitCommandManager extends CommandManager<
             Object nmsPlayer = entityField.get(player);
             if (nmsPlayer != null) {
                 Field localeField;
+                String localeString = null;
+                Locale locale = null;
                 try {
                     localeField = nmsPlayer.getClass().getDeclaredField("locale");
+                    localeField.setAccessible(true);
+                    localeString = (String) localeField.get(nmsPlayer);
+                    if (localeString instanceof String) {
+                        String[] split = ACFPatterns.UNDERSCORE.split((String) localeString);
+                        locale = split.length > 1 ? new Locale(split[0], split[1]) : new Locale(split[0]);
+                    }
                 } catch (NoSuchFieldException ignored) {
-                    localeField = nmsPlayer.getClass().getDeclaredField("language");
+                    localeField = nmsPlayer.getClass().getDeclaredField("adventure$locale");
+                    localeField.setAccessible(true);
+                    locale = (Locale) localeField.get(nmsPlayer);
+                    if (locale instanceof Locale) {
+                        localeString = locale.toString();
+                    }
                 }
-                localeField.setAccessible(true);
-                Object localeString = localeField.get(nmsPlayer);
-                if (localeString instanceof String) {
+                if (locale != null && localeString != null) {
                     UUID playerUniqueId = player.getUniqueId();
                     if (!localeString.equals(issuersLocaleString.get(playerUniqueId))) {
-                        String[] split = ACFPatterns.UNDERSCORE.split((String) localeString);
-                        Locale locale = split.length > 1 ? new Locale(split[0], split[1]) : new Locale(split[0]);
                         Locale prev = issuersLocale.put(playerUniqueId, locale);
-                        issuersLocaleString.put(playerUniqueId, (String) localeString);
+                        issuersLocaleString.put(playerUniqueId, localeString);
                         if (!Objects.equals(locale, prev)) {
                             this.notifyLocaleChange(getCommandIssuer(player), prev, locale);
                         }
```

**Comment by chickeneer** [comment]
I have pushed and deployed a fix for this. I was still unable to test it - but unless I did something real stupid - I can't imagine this not working for the reported issue.

**Comment by nossr50** [comment]
@chickeneer confirmed that this is fixed on my end

**Comment by andrewkm** [comment]
Confirmed fixed here as well, many thanks! <3

**Comment by BGHDDevelopment** [comment]
Just tested this, and when running 0.5.1 on the latest 1.20.2 paper build still getting this error:
`[20:10:25 INFO]: [ACF] Can't read players locale, you will be unable to automatically detect players language. Only Bukkit 1.7+ is supported for this.
[20:10:25 INFO]: [ACF] java.lang.NoSuchFieldException: locale`

**Comment by chickeneer** [comment]
> Just tested this, and when running 0.5.1 on the latest 1.20.2 paper build still getting this error:

There must be something factually incorrect about this statement. It should not be possible to get that error under the described scenario.

**Comment by BGHDDevelopment** [comment]
> > Just tested this, and when running 0.5.1 on the latest 1.20.2 paper build still getting this error:
> 
> There must be something factually incorrect about this statement. It should not be possible to get that error under the described scenario.

After further testing, it only appears for me when using acf-bukkit, switched to acf-paper in the pom.xml, and it has disappeared. Confused about the reasoning myself, as far as I could tell there is no reason with the changes made. Tried 2 different projects with the same results, perhaps it's something weird with my local development environment.

**Comment by chickeneer** [comment]
the latest acf-bukkit jar does have that new code in it. So that is strange.
Could try mvn -U. Which forces the snapshot version to be updated.
